---
title: "Otolith Sr Data Analysis"
output:
  html_document:
    theme: united
    highlight: tango
---

### Read data

```{r,}
#Read data and extract variables for analysis
df_oto <- df_oto <- read.csv("Data/larval oto chem age.csv", header = T)
df_oto1 <- df_oto[,c("year","location","otoSr.ppm")]
#convert year to categorical variable
df_oto1$year <- as.factor(df_oto1$year)
summary(df_oto1)

```

### ANOVA

```{r,}
#Test effects of Location (two rivers), Year, and Location*Year interaction on Otolith Sr 
anova1 <- aov(otoSr.ppm ~ location*year, data=df_oto1)
summary(anova1)

```

### Tukey HSD test

```{r, }
#TukeyHSD test
TukeyHSD(anova1)
```

### Basic Boxplot

```{r, fig.align='center', fig.width=9, fig.asp=0.7}
boxplot(otoSr.ppm ~ year, data=df_oto1, boxfill=rgb(1, 1, 1, alpha=1), border=rgb(1, 1, 1, alpha=1), xlab="Year",ylab="Otolith [Sr](ppm)", cex.lab=1.3)
boxplot(otoSr.ppm ~ year, data=df_oto1[which(df_oto1$location=="Maumee"),], xaxt = "n", add = TRUE, boxfill="white",boxwex=0.3, at=1:7 - 0.15)
boxplot(otoSr.ppm ~ year, data=df_oto1[which(df_oto1$location=="Sandusky"),], xaxt = "n", add = TRUE, boxfill="grey",boxwex=0.3, at=1:7 + 0.15)

```

### ggplot2 Boxplot
```{r,fig.align='center', fig.width=9, fig.asp=0.7}
library(ggplot2)

ggplot(data=df_oto1, aes(x=year, y=otoSr.ppm, fill=location))+
  geom_boxplot()+
  scale_fill_manual(values = c("white","grey"))+
  xlab("Year")+ylab("Otolith [Sr](ppm)")+
  theme_bw()+
  theme(panel.grid.major = element_blank(), panel.grid.minor=element_blank(),
        axis.title.x=element_text(size=16, colour = "black", margin = unit(c(6, 0, 0, 0), "mm")),
        axis.title.y=element_text(size=16, colour = "black", margin = unit(c(0, 5, 0, 0), "mm")),
        axis.text=element_text(size=14, colour = "black"),
        legend.position="none")+
  annotate("text",x=1:7-0.2, y=c(1600,1200,1200,1600,1200,1500,1400), label=c("a","a","a","a","a","a","a"), size=6)+
  annotate("text",x=1:7+0.2, y=c(2000,3200,2400,3200,1500,2900,2800), label=c("b","bc","bd","cd","ae","cd","bce"), size=6)


```


